### ISSUE TITLE
有分析中文的性能比USTC-NELSLIP模型差吗

### ISSUE THREAD

**Issue by wn1652400018** [Alibaba-NLP/KB-NER#1]
我看其他语种绝大多数都是遥遥领先第二名，只是在中文上比起最好的模型要差不少，请问有分析是什么原因吗？

**Comment by wangxinyu0922** [comment]
我参考了其他几个队伍的paper，目前的结论是在中文NER上可能是因为其他队伍主要使用了lexicon信息和并且用基于wiki的实体字典Gazetteer来做NER，从而带来了提升比较明显。我们的方法没有专门针对中文加入lexicon信息或者其他的优化，从而导致了差距。

我们在分析中文数据的时候感觉整个数据的句子都比较难读懂，感觉怀疑可能是用翻译等方法得到的句子和标注，在比赛结果上也可以看出来中文即使是最高结果也比其他语言都要低。目前multiconer数据的paper没出来，暂时不太确定是怎么生成的标注。给我的感觉是在这种句子不太好数据的情况下可能Gazetteer的优势更大一些，我们的sentence retrieval的方法在句子不太好的情况下检索结果也相应的会差一些。

不过这些分析可能都需要进行实验验证，你如果有兴趣的话可以试一下:)

**Comment by wn1652400018** [comment]
谢谢。



---原始邮件---
发件人: "Xinyu ***@***.***&gt;
发送时间: 2022年3月15日(周二) 下午2:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Alibaba-NLP/KB-NER] 有分析中文的性能比USTC-NELSLIP模型差吗 (Issue #1)




 
我参考了其他几个队伍的paper，目前的结论是在中文NER上可能是因为其他队伍主要使用了lexicon信息和并且用基于wiki的实体字典Gazetteer来做NER，从而带来了提升比较明显。我们的方法没有专门针对中文加入lexicon信息或者其他的优化，从而导致了差距。
 
我们在分析中文数据的时候感觉整个数据的句子都比较难读懂，感觉怀疑可能是用翻译等方法得到的句子和标注，在比赛结果上也可以看出来中文即使是最高结果也比其他语言都要低。目前multiconer数据的paper没出来，暂时不太确定是怎么生成的标注。给我的感觉是在这种句子不太好数据的情况下可能Gazetteer的优势更大一些，我们的sentence retrieval的方法在句子不太好的情况下检索结果也相应的会差一些。
 
不过这些分析可能都需要进行实验验证，你如果有兴趣的话可以试一下:)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
