### ISSUE TITLE
您好 请问该怎样获取数据集中对应的图像资源

### ISSUE THREAD

**Issue by Delicate2000** [Alibaba-NLP/KB-NER#12]
我下载了下方链接的数据集 ITA: Image-Text Alignments for Multi-Modal Named Entity Recognition
Our preprocessed datasets: [[OneDrive]](https://1drv.ms/u/s!Am53YNAPSsodhPEnSbEMTnsmdsiceg?e=f55rbp)
其中img文件夹下的文件是图片id。twitter15和twitter17两个数据集对应的图片资源已在别的论文链接中找到，但snap数据集对应的图片资源未找到，请问我该怎样获取。any response would be appreciated.

**Comment by wangxinyu0922** [comment]
https://github.com/Multimodal-NER/RpBERT/issues/1

**Comment by Delicate2000** [comment]
Thanks very much
