### ISSUE TITLE
资源链接失效

### ISSUE THREAD

**Issue by letiantony** [Alibaba-NLP/KB-NER#2]
hi，非常棒的工作，想复现实验一下，但是资源链接都失效，有空可以补一下吗？

**Comment by wangxinyu0922** [comment]
您好，请问是哪个链接失效了？我测试了一下应该大部分都可以使用

**Comment by Mint-hfut** [comment]
您好，ITA文件为什么找不到了？在《ITA: Image-Text Alignments for Multi-Modal Named Entity Recognition》这篇文章的代码

**Comment by wangxinyu0922** [comment]
> 您好，ITA文件为什么找不到了？在《ITA: Image-Text Alignments for Multi-Modal Named Entity Recognition》这篇文章的代码

您好，ITA的代码和数据会在近期放出。

**Comment by Mint-hfut** [comment]
好的，非常感谢

**Comment by Mint-hfut** [comment]
坐等ITA代码😁

**Comment by wangxinyu0922** [comment]
> 坐等ITA代码😁

ITA 代码已经更新了https://github.com/Alibaba-NLP/KB-NER/tree/main/ITA

**Comment by Mint-hfut** [comment]
请问能提供一份独立的代码吗？要求可能有点过分，您别介意。

**Comment by wangxinyu0922** [comment]
> 请问能提供一份独立的代码吗？要求可能有点过分，您别介意。

没太懂为什么有这个需求，独立的代码和目前这个没区别吧？
