### ISSUE TITLE
Running pre-trained models for inference on unlabelled data

### ISSUE THREAD

**Issue by vasari-kg** [Alibaba-NLP/KB-NER#4]
Hello,

Thanks for the effort of putting this project in open-source.
Do you by chance plan to provide source code or commands for running inference with pre-trained models on unlabelled data.
Thanks in advance.

Best regards,
Cristian Santini

**Comment by wangxinyu0922** [comment]
Hi, I have updated the guide for predicting files, you may refer to [this](https://github.com/Alibaba-NLP/KB-NER#predict-files)
