### ISSUE TITLE
Using system in production

### ISSUE THREAD

**Issue by Dimiftb** [Alibaba-NLP/KB-NER#6]
Hi there, 

Is it possible to use your system for inference in production? If yes what is the easiest way to achieve that?

Thanks

**Comment by wangxinyu0922** [comment]
Currently, the easiest way is following the readme for inference.

**Comment by JiangYong2014** [comment]
hi @Dimiftb , we have deployed the model at modelscope. With four lines of code, you can obtain a NER model for production. 

https://modelscope.cn/models/damo/nlp_raner_named-entity-recognition_english-large-generic/summary
