### ISSUE TITLE
Trained Models download link occurs error,help~~~

### ISSUE THREAD

**Issue by qwioer1** [Alibaba-NLP/KB-NER#8]

**Comment by wangxinyu0922** [comment]
What exactly the error is?

**Comment by qwioer1** [comment]
**Internal Server Error**

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

![图片](https://user-images.githubusercontent.com/44193756/182987728-33d9411f-b850-436d-834e-d1717dfc498c.png)

**Comment by wangxinyu0922** [comment]
你可能需要翻墙
